[application]
port = 8080
host = "127.0.0.1"
base_url = "http://127.0.0.1"
hmac_secret = "super-duper-hmac-secret-super-duper-hmac-secret-super-duper-hmac-secret-super-duper-hmac-secret"


[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database_name = "bubble_services"
require_ssl = false
